### ISSUE TITLE
API Works for people/?page=1 but don't work for people/?page=2

### ISSUE THREAD

**Issue by cml97** [phalt/swapi#113]
I am working on a Star Wars app that uses data in SWAPI. In android, I am working with retrofit but when I sending a request for **people/?page=1**, it works fine. When **people/?page=2**, it returns an exception 
`@GET("people/?page=1")
    fun getSecondPage(): Call<AllPeople>`
Luke Skywalker
    C-3PO
    R2-D2
    Darth Vader
    Leia Organa
    Owen Lars
    Beru Whitesun lars
    R5-D4
    Biggs Darklighter
    Obi-Wan Kenobi
--------------------------------------------------------------------------------------------------------------
`@GET("people/?page=2")`
W/System.err: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "unknown"
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
    Caused by: java.lang.NumberFormatException: For input string: "unknown"
        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
        at java.lang.Double.parseDouble(Double.java:547)
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
    	... 18 more

**Comment by phalt** [comment]
I'm not familiar with java but `Caused by: java.lang.NumberFormatException: For input string: "unknown"` this looks like something in your code is going wrong when you pass in the page number

**Comment by cml97** [comment]
I found the problem. I was creating my own results modal but I must take the results in JSONArray format. Thanks for answer and also your Swapi API :)

**Comment by phalt** [comment]
@cml97 no problems, enjoy!
